### ISSUE TITLE
Show People without #actions

### ISSUE THREAD

**Issue by shabegom** [zsviczian/obsidian-stakeholder-actions#18]
In the Person view I’d like to see tasks where a person is mentioned even if they don’t have one of the specified action tags.

This would mean I could be more flexible in mentioning people in tasks and still have them sorted into a view. 

Current Workaround: I’ve changed one of the tags to (.*)

example
- [ ] Give a big ol howdy to [[People/John Smith]]

**Comment by zsviczian** [comment]
so I am not sure about this. your may be able to use the misc snippet for this. But, it is by design that only the first person mentioned in a task is picked up as the action party because then I can mention others in the action without polluting the view.

**Comment by shabegom** [comment]
I'm going to close this. I misunderstood the purpose of the view.
