### ISSUE TITLE
Exclusion Pattern

### ISSUE THREAD

**Issue by shabegom** [zsviczian/obsidian-stakeholder-actions#19]
Would be great to supply an exclusion pattern to not pickup tasks that match the pattern. 

Use Case:
My daily agenda is inserted as a list of tasks so the Day Planner plugin picks it up. Day Planner automatically marks the tasks as done when the time has passed. I could supply a Timestamp pattern to exclude these tasks: \d{2}:\d{2}

**Comment by zsviczian** [comment]
Implemented in v0.5
