### ISSUE TITLE
Option to exclude Template folder from task list

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/obsidian-stakeholder-actions#2]

**Comment by roamhacker** [comment]
Yes a way to exclude folders would be helpful.

**Comment by zsviczian** [comment]
Added in alpha v0.4
I have added two options, to exclude a path beginning with a string, and to exclude a path or filename containing a special string.
The path is case-sensitive and intended to exclude the Templates/ folder. The filename is case insensitive and intended to exclude a special type of file such as Checklists (e.g. "shopping checklist.md", "Checklist for business trip packing.md", "Holiday checklist.md", etc.)
